// ============================================================================
// data/processData.ts
// 「財務シミュレーション・マスターモデル（プロセス1〜7横展開版）」および
// 各プロセスのベストプラクティス定義書（ROI・効果指標）から構造化したデータ。
// Supabase未接続時は本ファイルがそのままダッシュボードの表示データになる。
// 数値のうち ASSUMPTION 由来のものは実運用時に自社実績値へ置換すること。
// ============================================================================

import type {
  ProcessMetric,
  TrendMetric,
  PortfolioSummary,
  EffectPool,
} from "@/lib/types";

export const effectPools: EffectPool[] = [
  { id: "pool-01", name: "調達コスト変動プール" },
  {
    id: "pool-02",
    name: "供給停止・機会損失プール",
    overlapNote: "過剰在庫の保管コスト側面はPool-06と一部重複可能性あり（按分要）",
  },
  { id: "pool-03", name: "稼働・生産性ロスプール" },
  {
    id: "pool-04",
    name: "品質損失プール",
    overlapNote: "プロセス1のトレーサビリティ施策等と同時実施時は上限管理必須",
  },
  { id: "pool-05", name: "物流・輸送コストプール" },
  {
    id: "pool-06",
    name: "保管・在庫コストプール",
    overlapNote: "Pool-02（過剰在庫側面）と重複しうる部分は按分管理",
  },
  { id: "pool-07", name: "環境・資源循環コストプール" },
];

export const processMetrics: ProcessMetric[] = [
  {
    id: "p1",
    order: 1,
    key: "P1-01",
    processName: "調達・購買",
    stageLabel: "上流",
    initiative: "国際コモディティ価格急変検知ダッシュボード＋マルチソーシング体制構築",
    pool: "pool-01",
    financial: {
      capexOku: 1.2,
      opexOkuPerYear: 0.18,
      opexNature: "system",
      netImpactOkuPerYear: 1.9,
      ebitRoiPercent: 143,
      staticPaybackYears: 0.7,
      effectivePaybackYears: 0.95,
      timeToValueMonths: 3,
    },
    benchmarks: [
      {
        id: "p1-b1",
        label: "調達コスト（対市場価格乖離率）",
        unit: "%",
        companyValue: 3.2,
        industryAvg: 6.5,
        target: 3.0,
        direction: "lower-is-better",
      },
      {
        id: "p1-b2",
        label: "価格ヘッジによるコスト変動幅抑制率",
        unit: "%",
        companyValue: 34,
        industryAvg: 22,
        target: 40,
        direction: "higher-is-better",
      },
    ],
    evidenceNote:
      "IMF Primary Commodity Prices／World Bank Pink Sheet、帝国データバンク仕入単価DI（2025年3月：上昇75.5%、40か月連続7割超）",
    kpiNote: "価格ヘッジによる原材料コスト変動幅の抑制：業界平均比▲30〜50%（中央値40%採用）",
    ownerFunctions: ["SCM本部・調達戦略", "品質保証部・購買品質", "工場調達・生産管理"],
    status: "on-track",
  },
  {
    id: "p2",
    order: 2,
    key: "P2-01",
    processName: "受入・品質保証",
    stageLabel: "上流",
    initiative: "AI画像認識による異物・欠陥自動検査システム導入",
    pool: "pool-04",
    financial: {
      capexOku: 5.0,
      opexOkuPerYear: 0.5,
      opexNature: "system",
      netImpactOkuPerYear: 4.8,
      ebitRoiPercent: 86,
      staticPaybackYears: 1.16,
      effectivePaybackYears: 1.66,
      timeToValueMonths: 6,
    },
    benchmarks: [
      {
        id: "p2-b1",
        label: "検査効率（AI異物検知率）",
        unit: "pt",
        companyValue: 24,
        industryAvg: 12,
        target: 25,
        direction: "higher-is-better",
      },
      {
        id: "p2-b2",
        label: "受入〜製造投入リードタイム短縮率",
        unit: "%",
        companyValue: 38,
        industryAvg: 20,
        target: 40,
        direction: "higher-is-better",
      },
    ],
    evidenceNote: "US FDA Import Refusals／EU RASFF Window、厚生労働省 輸入食品監視統計",
    kpiNote: "品質事故（違反／リコール）発生件数：年間2件→0.5件（75%削減）",
    ownerFunctions: ["品質保証部・品質保証本部", "工場品質保証・受入検査", "SCM本部・トレーサビリティ管理"],
    status: "on-track",
  },
  {
    id: "p3",
    order: 3,
    key: "P3-01",
    processName: "生産・製造",
    stageLabel: "中流",
    initiative: "IoTセンサー×AIによる予知保全（計画外停止ゼロ化）",
    pool: "pool-03",
    financial: {
      capexOku: 3.0,
      opexOkuPerYear: 0.45,
      opexNature: "system",
      netImpactOkuPerYear: 1.44,
      ebitRoiPercent: 33,
      staticPaybackYears: 3.03,
      effectivePaybackYears: 3.78,
      timeToValueMonths: 9,
    },
    benchmarks: [
      {
        id: "p3-b1",
        label: "OEE（設備総合効率）",
        unit: "pt",
        companyValue: 11,
        industryAvg: 0,
        target: 13,
        direction: "higher-is-better",
      },
      {
        id: "p3-b2",
        label: "計画外停止時間削減率",
        unit: "%",
        companyValue: 36,
        industryAvg: 18,
        target: 40,
        direction: "higher-is-better",
      },
    ],
    evidenceNote: "Elsevier／Springer 予知保全 国際論文、経済産業省 鉱工業指数（稼働率指数）",
    kpiNote: "計画外停止時間：前年比30〜50%削減（中央値40%採用）",
    ownerFunctions: ["工場長・生産管理・設備保全", "品質保証部・工程品質管理", "SCM本部・生産統括"],
    status: "watch",
  },
  {
    id: "p4",
    order: 4,
    key: "P4-01",
    processName: "一次保管・倉庫管理",
    stageLabel: "中流",
    initiative: "自動倉庫・AGV／AMR導入＋FEFO完全自動化",
    pool: "pool-06",
    financial: {
      capexOku: 4.0,
      opexOkuPerYear: 0.2,
      opexNature: "hardware",
      netImpactOkuPerYear: 0.84,
      ebitRoiPercent: 16,
      staticPaybackYears: 6.25,
      effectivePaybackYears: 6.75,
      timeToValueMonths: 6,
    },
    benchmarks: [
      {
        id: "p4-b1",
        label: "在庫回転率",
        unit: "%",
        companyValue: 14,
        industryAvg: 6,
        target: 20,
        direction: "higher-is-better",
      },
      {
        id: "p4-b2",
        label: "賞味期限切れ廃棄率削減率",
        unit: "%",
        companyValue: 13,
        industryAvg: 5,
        target: 15,
        direction: "higher-is-better",
      },
    ],
    evidenceNote: "JILS 自動倉庫・AGV/AMRマテハン機器統計、CBRE Japan Logistics MarketView、国土交通省 倉庫統計季報",
    kpiNote: "入出庫作業1人時あたり処理件数：導入前比30〜50%向上（中央値40%）／廃棄率：前年比10〜20%削減（中央値15%）",
    ownerFunctions: ["工場物流・倉庫運用", "品質保証部・倉庫品質管理", "SCM本部・物流企画・倉庫戦略"],
    status: "watch",
  },
  {
    id: "p5",
    order: 5,
    key: "P5-01",
    processName: "物流・動態管理",
    stageLabel: "中流",
    initiative: "バース予約システム＋積載効率最適化＋共同配送",
    pool: "pool-05",
    financial: {
      capexOku: 0.8,
      opexOkuPerYear: 0.12,
      opexNature: "system",
      netImpactOkuPerYear: 0.38,
      ebitRoiPercent: 33,
      staticPaybackYears: 3.05,
      effectivePaybackYears: 3.3,
      timeToValueMonths: 3,
    },
    benchmarks: [
      {
        id: "p5-b1",
        label: "輸送コスト（トラック削減率）",
        unit: "%",
        companyValue: 13,
        industryAvg: 6,
        target: 15,
        direction: "higher-is-better",
      },
      {
        id: "p5-b2",
        label: "トラック積載率向上",
        unit: "pt",
        companyValue: 11,
        industryAvg: 5,
        target: 12,
        direction: "higher-is-better",
      },
    ],
    evidenceNote: "Baltic Dry Index／Drewry World Container Index、国土交通省 物流2024年問題関連統計（2030年度34.1%不足試算）",
    kpiNote: "トラック積載率：業界平均比+10〜15ポイント／共同配送によるトラック削減：対象route比10〜20%（中央値15%）",
    ownerFunctions: ["工場物流・出荷管理", "品質保証部・輸送品質管理", "SCM本部・物流企画・輸送調達"],
    status: "on-track",
  },
  {
    id: "p6",
    order: 6,
    key: "P6-01",
    processName: "流通・販売",
    stageLabel: "下流",
    initiative: "AI需要予測×CPFR（卸・小売との共同需給計画）",
    pool: "pool-02",
    financial: {
      capexOku: 1.5,
      opexOkuPerYear: 0.225,
      opexNature: "system",
      netImpactOkuPerYear: 0.54,
      ebitRoiPercent: 21,
      staticPaybackYears: 4.76,
      effectivePaybackYears: 5.26,
      timeToValueMonths: 6,
    },
    benchmarks: [
      {
        id: "p6-b1",
        label: "廃棄ロス率（返品・値引きロス削減）",
        unit: "%",
        companyValue: 13,
        industryAvg: 5,
        target: 15,
        direction: "higher-is-better",
      },
      {
        id: "p6-b2",
        label: "需要予測誤差改善率",
        unit: "%",
        companyValue: 32,
        industryAvg: 15,
        target: 40,
        direction: "higher-is-better",
      },
    ],
    evidenceNote: "NielsenIQ／Kantar グローバル小売・購買動向調査、経済産業省 商業動態統計調査",
    kpiNote: "返品・値引きロス率、過剰在庫・廃棄損失率：ともに前年比10〜20%削減（中央値15%）",
    ownerFunctions: ["工場生産管理・出荷計画", "品質保証部・営業品質管理", "SCM本部・営業企画・需給管理"],
    status: "watch",
  },
  {
    id: "p7",
    order: 7,
    key: "P7-01",
    processName: "消費・リサイクル・循環",
    stageLabel: "最終",
    initiative: "静脈物流の複数業者分散契約＋Scope3算定精度向上（ガイドラインVer.2.8準拠）",
    pool: "pool-07",
    financial: {
      capexOku: 1.0,
      opexOkuPerYear: 0.15,
      opexNature: "system",
      netImpactOkuPerYear: 0.101,
      ebitRoiPercent: -4.9,
      staticPaybackYears: NaN, // 単年度回収不可（複数年評価要）
      effectivePaybackYears: NaN,
      timeToValueMonths: 12,
    },
    benchmarks: [
      {
        id: "p7-b1",
        label: "リサイクル収益（リサイクル材使用比率）",
        unit: "%",
        companyValue: 22,
        industryAvg: 18,
        target: 30,
        direction: "higher-is-better",
      },
      {
        id: "p7-b2",
        label: "廃棄物処理コスト変動抑制（価格転嫁遅れギャップ緩和率）",
        unit: "%",
        companyValue: 46,
        industryAvg: 0,
        target: 50,
        direction: "higher-is-better",
      },
    ],
    evidenceNote:
      "EEA Circular Economy Monitoring Framework、帝国データバンク 廃棄物処理業界動向（2026年2月：仕入価格上昇71.5%に対し価格転嫁45.8%）",
    kpiNote: "複数処理業者との契約分散により、廃棄物処理コストの変動幅を抑制（価格転嫁遅れギャップの緩和率50%と設定）",
    ownerFunctions: ["SCM本部・サステナビリティ推進・環境戦略", "品質保証部・お客様相談室連携", "製品開発・生産技術・環境管理"],
    status: "alert",
  },
];

export const trendMetrics: TrendMetric[] = [
  {
    id: "trend-ai-forecast",
    title: "AI需要予測・自動発注／計画立案",
    summary:
      "気象・トレンド・POSデータを需要予測エンジンに統合し、調達の先行発注から生産計画、出荷平準化までを連動させる取り組み。",
    relatedProcessIds: ["p1", "p3", "p5", "p6"],
    dataPoints: [
      { label: "需要予測誤差改善", value: 32, unit: "%" },
      { label: "欠品率", value: 0.8, unit: "%" },
    ],
    updatedAt: "2026-08-01",
  },
  {
    id: "trend-agv-robotics",
    title: "AGV／AMR・ロボティクスによる自動化",
    summary:
      "受入検査エリアから製造ライン、倉庫、出荷ドックまでの搬送・荷役を自動化し、ハンドリング時間と省人化を両立する取り組み。",
    relatedProcessIds: ["p2", "p3", "p4", "p5", "p6"],
    dataPoints: [
      { label: "対象拠点導入率", value: 41, unit: "%" },
      { label: "省人化率", value: 27, unit: "%" },
    ],
    updatedAt: "2026-08-01",
  },
  {
    id: "trend-traceability",
    title: "ブロックチェーン・トレーサビリティ",
    summary:
      "受入ロットからサプライヤー出荷情報、輸送中の温度・振動データまでを改ざん防止で連携し、リコール対応や品質クレーム原因究明を迅速化。",
    relatedProcessIds: ["p1", "p2", "p3", "p5", "p6", "p7"],
    dataPoints: [
      { label: "ハイリスク品目カバー率", value: 58, unit: "%" },
      { label: "原因ロット特定所要時間", value: 4, unit: "h" },
    ],
    updatedAt: "2026-08-01",
  },
  {
    id: "trend-scope3",
    title: "Scope3環境対応",
    summary:
      "環境省・経産省ガイドラインVer.2.8に準拠したScope3（15カテゴリ）算定精度の向上と、実測データ比率の継続的な引き上げ。",
    relatedProcessIds: ["p1", "p3", "p4", "p5", "p6", "p7"],
    dataPoints: [
      { label: "算定カバー率", value: 74, unit: "%" },
      { label: "実測データ比率", value: 46, unit: "%" },
    ],
    updatedAt: "2026-08-01",
  },
];

export const portfolioSummary: PortfolioSummary = {
  totalCapexOku: 16.5,
  totalOpexOkuPerYear: 1.825,
  totalNetImpactOkuPerYear: 10.0,
  weightedEbitRoiPercent: 50,
  blendedPaybackYearsRange: [2, 3],
};
